language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lucca1236/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lucca1236/docker-react npm run test